title: Hi
author: mialindroid
email: your-email@domain.com
description: This is a test page.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  mialindroid

show_excerpts: true # set to false to remove excerpts on the homepage
